providers = ["python"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python -c \"import backend.preprocess as p; p.run()\" && uvicorn main:app --host 0.0.0.0 --port $PORT"
